export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST'
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'

export const LOAD_CART_ITEMS_REQUEST = 'LOAD_CART_ITEMS_REQUEST'
export const LOAD_CART_ITEMS_FAILURE = 'LOAD_CART_ITEMS_FAILURE'
export const LOAD_CART_ITEMS_SUCCESS = 'LOAD_CART_ITEMS_SUCCESS'

export const ADD_CART_ITEM_REQUEST = 'ADD_CART_ITEM_REQUEST'
export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS'
export const ADD_CART_ITEM_FAILURE = 'ADD_CART_ITEM_FAILURE'

export const SET_QUANTITY_FOR_ITEM_REQUEST = 'SET_QUANTITY_FOR_ITEM_REQUEST'
export const SET_QUANTITY_FOR_ITEM_SUCCESS = 'SET_QUANTITY_FOR_ITEM_SUCCESS'
export const SET_QUANTITY_FOR_ITEM_FAILURE = 'SET_QUANTITY_FOR_ITEM_FAILURE'

export const CALCULATE_TOTAL_PRICE_REQUEST = 'CALCULATE_TOTAL_PRICE_REQUEST'
export const CALCULATE_TOTAL_PRICE_FAILURE = 'CALCULATE_TOTAL_PRICE_FAILURE'
export const CALCULATE_TOTAL_PRICE_SUCCESS = 'CALCULATE_TOTAL_PRICE_SUCCESS'
